### ISSUE TITLE
Error in trimming step

### ISSUE THREAD

**Issue by fjruizruano** [fethalen/Patchwork#36]
Hi!

I am trying to run Patchwork without compiling

`$ julia src/Patchwork.jl --contigs test/07673_dna.fa --reference test/07673_Alitta_succinea.fa --threads 1`

And I got this error message:

```
P A T C H W O R K
- Developers: Felix Thalén & Clara G. Köhne         - Cite      : In prep.
- Contact   : <felix.thalen@uni-goettingen.de>      - DIAMOND v.: 2.0.14
- Wiki      : github.com/fethalen/patchwork/wiki    - Threads   : 1
──────────────────────────────────────────────────────────────────────────
Building DIAMOND database...
Aligning query sequences against reference database...
Merging overlapping hits...
Trimming alignments...
ERROR: AssertionError: Can only concatenate
contigs from same species.
Stacktrace:
 [1] concatenate(regions::Main.Patchwork.AlignedRegionCollection, delimiter::Char)
   @ Main.Patchwork /proj/src/patchwork/src/alignmentconcatenation.jl:131
 [2] main()
   @ Main.Patchwork /proj/src/patchwork/src/Patchwork.jl:403
 [3] julia_main()
   @ Main.Patchwork /proj/src/patchwork/src/Patchwork.jl:459
 [4] top-level scope
   @ /proj/src/patchwork/src/Patchwork.jl:469
```
This is the output folder:
```
.
├── database.dmnd
├── diamond_blastx.log
├── diamond_makedb.log
├── diamond_out
│   └── ASUC@m.22314-423.tsv
├── plots
├── query_sequences
└── sequence_stats

```

Any clue?

Thanks in advance.

**Comment by fethalen** [comment]
Hi Francisco, 

The relevant part of the error message is in "Can only concatenate contigs from same species". There's an underlying assumption that you are only using a single species for the alignment (when using more than one taxa, look into `[multi_patchwork.sh](https://github.com/fethalen/Patchwork/blob/main/scripts/multi_patchwork.sh)`). The species is detected by splitting what comes before and after the at sign (`@`). If you use `07673_Alitta_succinea.fa` instead, there's only one DNA sequence from one species there. I think the other files are remnants form an older version where Patchwork this would've been possible. Totally understand the confusion but I hope that solves your problem!

**Comment by fjruizruano** [comment]
Hi Felix!

Thanks for your fast response and fixing the example file. Now it worked!

I have a couple of follow up questions about the output:
1. Is it usual to get stop codons in the resulting aminoacidic sequence.
2. Is is possible to the nucleotide sequence?

Thanks.

**Comment by fjruizruano** [comment]
Thanks a lot for the feedback. I will try with my data and see how it works.
Cheers!
