### ISSUE TITLE
Cannot install Patchwork on HPC

### ISSUE THREAD

**Issue by bastianheimburger** [fethalen/Patchwork#49]
Hi guys,

I'm trying to install Patchwork on our GWDG HPC at the University of Göttingen. Have you accomplished to do so?

I have tried everything but failed. I tried to install from source but Julia always gives me something like this: 

`(@patchwork) pkg> status --outdated -m
Status /home/uni08/bheimbu/.conda/envs/patchwork/share/julia/environments/patchwork/Manifest.toml`
`⌅ [28b8d3ca] GR v0.69.5 [<v0.70.1], (<v0.70.0): Plots`
`⌅ [d2c73de3] GR_jll v0.69.1+0 (<v0.70.0+1): GR`
`⌅ [e9f186c6] Libffi_jll v3.2.2+1 (<v3.4.4+0): Glib_jll, HarfBuzz_jll, Wayland_jll`
`⌅ [214eeab7] fzf_jll v0.29.0+0 (<v0.30.0+0): JLFzf`

Meaning that some Packages are outdated, however manually updating them fails also because dependencies are changing, breaking everything. 

I have created my conda environment with following command: 

`conda create -n patchwork -c bioconda -c conda-forge julia=1.8.2 diamond` and then `julia --project=. -e "import Pkg; Pkg.instantiate()"` and `julia --project=. src/Patchwork.jl --help`.

Any help is highly appreciated,

Bastian

ps: I'm sitting at Untere Karspüle 2, same building as you on the lower floor.

**Comment by ClaraKoehne** [comment]
Hello Bastian, 
if you're in office some time next week, I could come by and have a look at what's going on. I'm free on Monday, Wednesday and Thursday morning, or Tuesday early afternoon. At first, I also had trouble with the HPC, also with the conda installation. But there is the option of installing from source, I can show you how to do that - there are some additional peculiarities on the cluster (outdated files etc.), but I've found workarounds for the problems. Let me know if you'd like me to have a look. 
Cheers, Clara

**Comment by bastianheimburger** [comment]
Hi,

Mondaymorning sounds good. Does 10:30 am work for you?

Bastian

**Comment by ClaraKoehne** [comment]
Sure! I'll ring at the door then.

**Comment by bastianheimburger** [comment]
Hi,

can we make Tuesday, I'm not in office on Monday as I've just realized.

Cheers Bastian

**Comment by ClaraKoehne** [comment]
No problem. Is Tuesday at 1 pm okay?

**Comment by ClaraKoehne** [comment]
No problem! Is Tuesday at 1 pm okay?

**Comment by bastianheimburger** [comment]
Sry,

I‘ve forgotten to reply. Tuesday at 1 pm is fine.

See u then,

Bastian


Sent from my iPhone

On 18. Nov 2022, at 08:26, Clara Köhne ***@***.***> wrote:

﻿

No problem. Is Tuesday at 1 pm okay?
