### ISSUE TITLE
PackageCompiler: compiling nonincremental system image ERROR

### ISSUE THREAD

**Issue by qilu521** [fethalen/Patchwork#53]
Here's what happened when I Compile Patchwork
 [18m:45s] PackageCompiler: compiling nonincremental system image
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: warning: /root/software/ju                                                                                                                                               lia-1.8.2/lib/julia/libstdc++.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: warning: /root/software/ju                                                                                                                                               lia-1.8.2/lib/julia/libstdc++.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: warning: /root/software/ju                                                                                                                                               lia-1.8.2/lib/julia/libatomic.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: warning: /root/software/ju                                                                                                                                               lia-1.8.2/lib/julia/libatomic.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: warning: /root/software/ju                                                                                                                                               lia-1.8.2/lib/julia/libstdc++.so.6: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: warning: /root/software/ju                                                                                                                                               lia-1.8.2/lib/julia/libstdc++.so.6: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002

[root@localhost patchwork]# julia --project=. src/compile.jl . src/precompiled.jl OUTPUT_DIR
PackageCompiler: bundled artifacts:
  ├── Bzip2_jll - 1.444 MiB
  ├── Cairo_jll - 11.884 MiB
  ├── Expat_jll - 786.043 KiB
  ├── FFMPEG_jll - 26.314 MiB
  ├── Fontconfig_jll - 1.597 MiB
  ├── FreeType2_jll - 4.090 MiB
  ├── FriBidi_jll - 324.047 KiB
  ├── GLFW_jll - 554.408 KiB
  ├── GR_jll - 24.410 MiB
  ├── Gettext_jll - 13.968 MiB
  ├── Glib_jll - 16.549 MiB
  ├── Graphite2_jll - 302.039 KiB
  ├── HarfBuzz_jll - 2.960 MiB
  ├── JpegTurbo_jll - 4.167 MiB
  ├── LAME_jll - 904.166 KiB
  ├── LERC_jll - 629.045 KiB
  ├── LZO_jll - 899.784 KiB
  ├── Libffi_jll - 97.715 KiB
  ├── Libgcrypt_jll - 5.030 MiB
  ├── Libglvnd_jll - 4.996 MiB
  ├── Libgpg_error_jll - 1.590 MiB
  ├── Libiconv_jll - 1.955 MiB
  ├── Libmount_jll - 15.725 MiB
  ├── Libtiff_jll - 8.200 MiB
  ├── Libuuid_jll - 7.658 MiB
  ├── NodeJS
  │   └── nodejs_app - 70.889 MiB
  ├── Ogg_jll - 562.720 KiB
  ├── OpenSSL_jll - 12.358 MiB
  ├── OpenSpecFun_jll - 577.252 KiB
  ├── Opus_jll - 2.709 MiB
  ├── Pixman_jll - 5.407 MiB
  ├── Qt5Base_jll - 67.711 MiB
  ├── Vega
  │   └── vegalite_app - 139.263 MiB
  ├── VegaLite
  │   └── vegalite_app - [already bundled]
  ├── Wayland_jll - 1.325 MiB
  ├── Wayland_protocols_jll - 465.663 KiB
  ├── XML2_jll - 8.998 MiB
  ├── XSLT_jll - 1.687 MiB
  ├── Xorg_libX11_jll - 51.291 MiB
  ├── Xorg_libXau_jll - 134.889 KiB
  ├── Xorg_libXcursor_jll - 678.776 KiB
  ├── Xorg_libXdmcp_jll - 302.636 KiB
  ├── Xorg_libXext_jll - 2.235 MiB
  ├── Xorg_libXfixes_jll - 612.308 KiB
  ├── Xorg_libXi_jll - 5.838 MiB
  ├── Xorg_libXinerama_jll - 177.771 KiB
  ├── Xorg_libXrandr_jll - 1.273 MiB
  ├── Xorg_libXrender_jll - 1.432 MiB
  ├── Xorg_libpthread_stubs_jll - 5.074 KiB
  ├── Xorg_libxcb_jll - 11.389 MiB
  ├── Xorg_libxkbfile_jll - 1.513 MiB
  ├── Xorg_xcb_util_image_jll - 187.199 KiB
  ├── Xorg_xcb_util_jll - 142.044 KiB
  ├── Xorg_xcb_util_keysyms_jll - 82.065 KiB
  ├── Xorg_xcb_util_renderutil_jll - 116.603 KiB
  ├── Xorg_xcb_util_wm_jll - 701.915 KiB
  ├── Xorg_xkbcomp_jll - 770.177 KiB
  ├── Xorg_xkeyboard_config_jll - 5.271 MiB
  ├── Xorg_xtrans_jll - 241.450 KiB
  ├── Zstd_jll - 1.493 MiB
  ├── fzf_jll - 3.595 MiB
  ├── libaom_jll - 15.624 MiB
  ├── libass_jll - 1.088 MiB
  ├── libfdk_aac_jll - 8.467 MiB
  ├── libpng_jll - 976.110 KiB
  ├── libvorbis_jll - 1.119 MiB
  ├── x264_jll - 4.934 MiB
  ├── x265_jll - 5.982 MiB
  └── xkbcommon_jll - 1.373 MiB
  Total artifact file size: 597.765 MiB
✔ [03m:21s] PackageCompiler: compiling base system image (incremental=false)
Precompiling project...
  203 dependencies successfully precompiled in 566 seconds
✔ [18m:45s] PackageCompiler: compiling nonincremental system image
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: warning: /root/software/ju                                                                                                                                               lia-1.8.2/lib/julia/libstdc++.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: warning: /root/software/ju                                                                                                                                               lia-1.8.2/lib/julia/libstdc++.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: warning: /root/software/ju                                                                                                                                               lia-1.8.2/lib/julia/libatomic.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: warning: /root/software/ju                                                                                                                                               lia-1.8.2/lib/julia/libatomic.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: warning: /root/software/ju                                                                                                                                               lia-1.8.2/lib/julia/libstdc++.so.6: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: warning: /root/software/ju                                                                                                                                               lia-1.8.2/lib/julia/libstdc++.so.6: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002

**Comment by fethalen** [comment]
[The updated compilation procedure](https://github.com/fethalen/Patchwork/wiki/4.-Installation#23-compiling-patchwork-optional) should solve the issues you were having. If not, consider reopening this issue.
