### ISSUE TITLE
isoverlapping` not defined？

### ISSUE THREAD

**Issue by deyuanyang** [fethalen/Patchwork#54]
Hi，

Would you mind helping me solve it？

(base) deyuan@cody-monkey:~/4T/Pacthwork$ sudo singularity run --bind /home/deyuan/4T/Pacthwork/output:/output /home/deyuan/Softs/Patchwork-main/docker/patchwork.sif --contigs /home/deyuan/4T/Pacthwork/contigs.fasta --reference /home/deyuan/4T/Pacthwork/Am.faa --output-dir /output
[sudo] password for deyuan: 
P A T C H W O R K
- Developers: Felix Thalén & Clara G. Köhne         - Cite      : In prep.
- Contact   : <felix.thalen@cardio-care.ch>         - DIAMOND v.: 2.1.8
- Wiki      : github.com/fethalen/patchwork/wiki    - Threads   : 72
──────────────────────────────────────────────────────────────────────────
Building DIAMOND database...
Aligning query sequences against reference database...
Merging overlapping hits...
Trimming alignments...
ERROR: UndefVarError: `isoverlapping` not defined
Stacktrace:
 [1] mergeoverlaps(regions::Patchwork.AlignedRegionCollection, sorted::Bool, iteration::Int64, maxiterate::Int64)
   @ Patchwork /opt/patchwork/src/alignedregioncollection.jl:204
 [2] mergeoverlaps
   @ /opt/patchwork/src/alignedregioncollection.jl:193 [inlined]
 [3] main()
   @ Patchwork /opt/patchwork/src/Patchwork.jl:511
 [4] julia_main()
   @ Patchwork /opt/patchwork/src/Patchwork.jl:574
 [5] top-level scope
   @ none:1
(base) deyuan@cody-monkey:~/4T/Pacthwork$

**Comment by deyuanyang** [comment]
I'm unable to find Patchwork v0.5.6. 

Could you please provide more guidance on using this software? I heard about this soft from Dazuo Yang quite some time ago. I want to use it in my project. But I'm not familiar with Julia, it is too challenging for me.


Here are some issues when I  used this software:


(base) cody@cody:~/opt/patchwork$ /home/cody/opt/patchwork/src/Patchwork.jl  -h
/home/cody/opt/patchwork/src/Patchwork.jl: line 5: module: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 7: using: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 8: using: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 9: using: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 10: using: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 11: using: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 12: using: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 13: using: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 14: using: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 15: using: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 16: using: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 17: using: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 18: using: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 20: import: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 21: import: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 22: import: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 23: import: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 24: import: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 25: import: command not found
/home/cody/opt/patchwork/src/Patchwork.jl: line 27: syntax error near unexpected token `"sequenceidentifier.jl"'
/home/cody/opt/patchwork/src/Patchwork.jl: line 27: `include("sequenceidentifier.jl")'
(base) cody@cody:~/opt/patchwork$ /home/cody/opt/patchwork/src/Patchwork.jl  --version



(base) cody@cody:~/opt/patchwork$ julia --project=. src/Patchwork.jl  --contigs test/07673_dna.fa --reference test/07673_Alitta_succinea.fa
P A T C H W O R K v0.6.8
- Developers: Felix Thalén & Clara G. Köhne       - Cite      : 10.1093/gbe/evad227
- Contact   : <felix.thalen@cardio-care.ch>       - DIAMOND v.: 2.1.8
- Wiki      : github.com/fethalen/patchwork/wiki  - Threads   : 128
──────────────────────────────────────────────────────────────────────────
Sequence data file format detected: FASTA
ERROR: UndefVarError: `nucleotides` not defined
Stacktrace:
 [1] fasta_countrecords
   @ ~/opt/patchwork/src/fasta.jl:253 [inlined]
 [2] countrecords(sequencefile::String, sequencefile_format::String)
   @ Main.Patchwork ~/opt/patchwork/src/checkinput.jl:442
 [3] main()
   @ Main.Patchwork ~/opt/patchwork/src/Patchwork.jl:481
 [4] macro expansion
   @ ./timing.jl:273 [inlined]
 [5] julia_main()
   @ Main.Patchwork ~/opt/patchwork/src/Patchwork.jl:588
 [6] top-level scope
   @ ~/opt/patchwork/src/Patchwork.jl:598
 [7] include(mod::Module, _path::String)
   @ Base ./Base.jl:457
 [8] exec_options(opts::Base.JLOptions)
   @ Base ./client.jl:307
 [9] _start()
   @ Base ./client.jl:522
(base) cody@cody:~/opt/patchwork$

**Comment by deyuanyang** [comment]
(base) cody@cody:~/opt/patchwork$ /home/cody/opt/patchwork/build/compiled/bin/patchwork --contigs test/07673_dna.fa --reference test/07673_Alitta_succinea.fa
P A T C H W O R K v0.6.8
- Developers: Felix Thalén & Clara G. Köhne       - Cite      : 10.1093/gbe/evad227
- Contact   : <felix.thalen@cardio-care.ch>       - DIAMOND v.: 2.1.8
- Wiki      : github.com/fethalen/patchwork/wiki  - Threads   : 128
──────────────────────────────────────────────────────────────────────────
Sequence data file format detected: FASTA
ERROR: UndefVarError: `nucleotides` not defined
Stacktrace:
 [1] fasta_countrecords
   @ ~/opt/patchwork/src/fasta.jl:253 [inlined]
 [2] countrecords(sequencefile::String, sequencefile_format::String)
   @ Patchwork ~/opt/patchwork/src/checkinput.jl:442
 [3] main()
   @ Patchwork ~/opt/patchwork/src/Patchwork.jl:481
 [4] macro expansion
   @ ./timing.jl:273 [inlined]
 [5] julia_main()
   @ Patchwork ~/opt/patchwork/src/Patchwork.jl:588
 [6] top-level scope
   @ none:1

**Comment by fethalen** [comment]
Hello,

You have installed Julia correctly, the error was on my side. I had fixed
an issue in the function that counts the number of nucleotides but that fix
was not uploaded. I have uploaded the fix now (Patchwork version 0.6.9).
Please try with this new version to see if you're still experiencing any
issues!

Den ons 24 apr. 2024 kl 19:04 skrev deyuanyang ***@***.***>:

**Comment by fethalen** [comment]
No need to go for version 0.5.6, it's just that this was the latest version at the time. Always use the latest version!

**Comment by deyuanyang** [comment]
(base) cody@cody:~/opt/test_patc$ patchwork  --contigs  contigs.fasta     --reference  07673.fa 
P A T C H W O R K v0.6.9
- Developers: Felix Thalén & Clara G. Köhne       - Cite      : 10.1093/gbe/evad227
- Contact   : <felix.thalen@cardio-care.ch>       - DIAMOND v.: 2.1.8
- Wiki      : github.com/fethalen/patchwork/wiki  - Threads   : 128
──────────────────────────────────────────────────────────────────────────
Sequence data file format detected: FASTA
Building DIAMOND database...
Aligning query sequences against reference database...
Merging overlapping hits...
Trimming alignments...
ERROR: BoundsError: attempt to access 27×27 Matrix{Int64} at index [7, 28]
Stacktrace:
  [1] getindex
    @ ./essentials.jl:14 [inlined]
  [2] getindex
    @ ~/.julia/packages/BioAlignments/I6ecx/src/submat.jl:82 [inlined]
  [3] run!(nw::BioAlignments.NeedlemanWunsch{Int64}, a::BioSequences.LongAA, b::BioSequences.LongAA, submat::BioAlignments.SubstitutionMatrix{BioSymbols.AminoAcid, Int64}, start_gap_open_a::Int64, start_gap_extend_a::Int64, middle_gap_open_a::Int64, middle_gap_extend_a::Int64, end_gap_open_a::Int64, end_gap_extend_a::Int64, start_gap_open_b::Int64, start_gap_extend_b::Int64, middle_gap_open_b::Int64, middle_gap_extend_b::Int64, end_gap_open_b::Int64, end_gap_extend_b::Int64)
    @ BioAlignments ~/.julia/packages/BioAlignments/I6ecx/src/pairwise/algorithms/needleman_wunsch.jl:41
  [4] run!(nw::BioAlignments.NeedlemanWunsch{Int64}, a::BioSequences.LongAA, b::BioSequences.LongAA, submat::BioAlignments.SubstitutionMatrix{BioSymbols.AminoAcid, Int64}, gap_open::Int64, gap_extend::Int64)
    @ BioAlignments ~/.julia/packages/BioAlignments/I6ecx/src/pairwise/algorithms/needleman_wunsch.jl:184
  [5] pairalign(::BioAlignments.GlobalAlignment, a::BioSequences.LongAA, b::BioSequences.LongAA, score::BioAlignments.AffineGapScoreModel{Int64}; score_only::Bool, banded::Bool, lower_offset::Int64, upper_offset::Int64)
    @ BioAlignments ~/.julia/packages/BioAlignments/I6ecx/src/pairwise/pairalign.jl:103
  [6] pairalign
    @ ~/.julia/packages/BioAlignments/I6ecx/src/pairwise/pairalign.jl:78 [inlined]
  [7] pairalign_global (repeats 2 times)
    @ ~/opt/Patchwork-main/src/alignment.jl:21 [inlined]
  [8] maskgaps(alignment::BioAlignments.PairwiseAlignment{BioSequences.LongAA, BioSequences.LongAA}, dna::BioSequences.LongSequence{BioSequences.DNAAlphabet{4}})
    @ Patchwork ~/opt/Patchwork-main/src/alignmentconcatenation.jl:290
  [9] main()
    @ Patchwork ~/opt/Patchwork-main/src/Patchwork.jl:524
 [10] macro expansion
    @ ./timing.jl:273 [inlined]
 [11] julia_main()
    @ Patchwork ~/opt/Patchwork-main/src/Patchwork.jl:588
 [12] top-level scope
    @ none:1
(base) cody@cody:~/opt/test_patc$

**Comment by fethalen** [comment]
I think this error is due to a recent change to the masking algorithm. Can
you rerun your analysis using Patchwork v0.7.0? I just uploaded it to
GitHub.

Den tors 25 apr. 2024 kl 11:36 skrev deyuanyang ***@***.***>:

**Comment by deyuanyang** [comment]
(base) cody@cody:~/opt/test_patc$ /home/cody/opt/patchwork/build/compiled/bin/patchwork  --contigs  contigs.fasta     --reference  07673.fa 
P A T C H W O R K v0.7.0
- Developers: Felix Thalén & Clara G. Köhne       - Cite      : 10.1093/gbe/evad227
- Contact   : <felix.thalen@cardio-care.ch>       - DIAMOND v.: 2.1.8
- Wiki      : github.com/fethalen/patchwork/wiki  - Threads   : 128
──────────────────────────────────────────────────────────────────────────
Sequence data file format detected: FASTA
Building DIAMOND database...
Aligning query sequences against reference database...
Merging overlapping hits...
Trimming alignments...
ERROR: BoundsError: attempt to access 27×27 Matrix{Int64} at index [11, 28]
Stacktrace:
  [1] getindex
    @ ./essentials.jl:14 [inlined]
  [2] getindex
    @ ~/.julia/packages/BioAlignments/I6ecx/src/submat.jl:82 [inlined]
  [3] run!(nw::BioAlignments.NeedlemanWunsch{Int64}, a::BioSequences.LongAA, b::BioSequences.LongAA, submat::BioAlignments.SubstitutionMatrix{BioSymbols.AminoAcid, Int64}, start_gap_open_a::Int64, start_gap_extend_a::Int64, middle_gap_open_a::Int64, middle_gap_extend_a::Int64, end_gap_open_a::Int64, end_gap_extend_a::Int64, start_gap_open_b::Int64, start_gap_extend_b::Int64, middle_gap_open_b::Int64, middle_gap_extend_b::Int64, end_gap_open_b::Int64, end_gap_extend_b::Int64)
    @ BioAlignments ~/.julia/packages/BioAlignments/I6ecx/src/pairwise/algorithms/needleman_wunsch.jl:41
  [4] run!(nw::BioAlignments.NeedlemanWunsch{Int64}, a::BioSequences.LongAA, b::BioSequences.LongAA, submat::BioAlignments.SubstitutionMatrix{BioSymbols.AminoAcid, Int64}, gap_open::Int64, gap_extend::Int64)
    @ BioAlignments ~/.julia/packages/BioAlignments/I6ecx/src/pairwise/algorithms/needleman_wunsch.jl:184
  [5] pairalign(::BioAlignments.GlobalAlignment, a::BioSequences.LongAA, b::BioSequences.LongAA, score::BioAlignments.AffineGapScoreModel{Int64}; score_only::Bool, banded::Bool, lower_offset::Int64, upper_offset::Int64)
    @ BioAlignments ~/.julia/packages/BioAlignments/I6ecx/src/pairwise/pairalign.jl:103
  [6] pairalign
    @ ~/.julia/packages/BioAlignments/I6ecx/src/pairwise/pairalign.jl:78 [inlined]
  [7] pairalign_global (repeats 2 times)
    @ ~/opt/patchwork/src/alignment.jl:21 [inlined]
  [8] maskgaps(alignment::BioAlignments.PairwiseAlignment{BioSequences.LongAA, BioSequences.LongAA}, dna::BioSequences.LongSequence{BioSequences.DNAAlphabet{4}})
    @ Patchwork ~/opt/patchwork/src/alignmentconcatenation.jl:290
  [9] main()
    @ Patchwork ~/opt/patchwork/src/Patchwork.jl:524
 [10] macro expansion
    @ ./timing.jl:273 [inlined]
 [11] julia_main()
    @ Patchwork ~/opt/patchwork/src/Patchwork.jl:588
 [12] top-level scope
    @ none:1
(base) cody@cody:~/opt/test_patc$

**Comment by fethalen** [comment]
There seems to be an error in the `maskalignment()` function in `alignmentconcatenation.jl`. I am unable to recreate the error you're having, using my own data. Do you think it would be possible to share a minimal example that triggers the error to my email? Data would only be used to fix this error and not for other purposes.

**Comment by fethalen** [comment]
I noticed that you're using the test data and I was able to recreate the issue using the file `07673.fa` as the reference. The issue is to do with the gaps `-` in that file not being handled correctly. I will create a patch but in the meantime, you could try the ungapped version `07673_dealigned.fa` or `07673_Alitta_virens.fa`. This worked for me!

**Comment by fethalen** [comment]
So in summary, do not use a reference file with any gap characters (`-`) in it for now until the patch has been released!

**Comment by deyuanyang** [comment]
OK, it's work now. So sorry to disturb you.

Many thanks for your help.

**Comment by deyuanyang** [comment]
It is cool software. I almost plan to use the UCE method in my project. Today, I tested this software on my samples for shallow genome-sequencing in 5Gb. This software has perfect performance compared to BUSCO

**Comment by deyuanyang** [comment]
Hi Felix,

Would you mind giving me some guidance on how to judge the output quality of Patchwork? I do not know, what kind of output can be used in the next analysis. 

Deyuan

**Comment by fethalen** [comment]
Hi Deyuan,

Look at the alignments! The `trimmed_alignments.txt` shows the final alignments, while the `untrimmed_alignments.txt` gives you the alignments before trimming. Do they look reasonable when taking the known distance between your input and reference sequence into account? Compare trimming and non-trimming. Is the trimming too aggressive? In this case, perhaps skip the sliding window process using `--no-trimming`. 

I usually like to use the `--ultra-sensitive` option, it's a little slower but should give you longer sequences. There are a ton of options to play around with. Maybe at least try a couple of different settings for the scoring of the alignments to see if you can get a better result than what you already have.

The output you use depends on your project. Personally, I was doing a phylogenomics project in which I took the sequences from `protein_query_sequences`  and used them in my downstream analysis. Since I am not familiar with the project you're doing, I'm not sure what to suggest here.

**Comment by deyuanyang** [comment]
Thank you very much for all of your suggestions.

I am building a molecular and morphology database for "Polychaetes" in the China Seas. I employed a shallow genome skimming method, sequencing 5-10Gb from each species. Additionally, I plan to use these data to construct a phylogeny of "Polychaetes".  Currently, only your software is suitable for exploring more molecular markers.

**Comment by fethalen** [comment]
Fantastic! I inferred the phylogeny of Nereididae for my PhD thesis. You can find it here: https://ediss.uni-goettingen.de/handle/11858/14427. There you will see the workflow that we ended up using, but there are many alternatives and considerations. What we did was to target single-copy genes.

I used the script [`multi_patchwork.sh`](https://github.com/fethalen/Patchwork/blob/main/scripts/multi_patchwork.sh) to combine the output of many runs into one.
